### PR TITLE
fix #5135 - include suboptimal algorithm responses in multiple choice options

### LINKED ISSUE #5135: Only correct responses showing for some multiple-choice questions
Currently, some questions are only showing correct options for multiple choice questions after a student has made four failed attempts to answer a question in Connect. This is because there are no human-graded suboptimal responses for the question. We should update the logic in the CMS to send back algorithmically suboptimal responses as well as human-graded suboptimal responses.

### PR DESCRIPTION
**Pull request by emilia-friedberg**
Addresses issue #5135

**Changes proposed in this pull request:**
- pull non-optimal responses rather than strictly `optimal: false` responses for multiple choice options

**If this is a visual change please attach screencaps of the new branch, making sure to censor user data**

**Has this branch been QA'd on staging?** no

**Have you updated the docs?** no

**Have the tests been updated?** no

**Reviewer:** @anathomical

### CODE REVIEW

File: services/QuillCMS/app/controllers/responses_controller.rb [hunk 1]
```diff
@@ -75,7 +75,7 @@ def responses_for_question
   def multiple_choice_options
     multiple_choice_options = Rails.cache.fetch("questions/#{params[:question_uid]}/multiple_choice_options", :expires_in => 900) do
       optimal_responses = Response.where(question_uid: params[:question_uid], optimal: true).order('count DESC').limit(2).to_a
-      sub_optimal_responses = Response.where(question_uid: params[:question_uid], optimal: false).order('count DESC').limit(2).to_a
+      sub_optimal_responses = Response.where(question_uid: params[:question_uid], optimal: [false, nil]).order('count DESC').limit(2).to_a
```
Comment (anathomical) [inline services/QuillCMS/app/controllers/responses_controller.rb]: This sort of feels like it might be a back-end data issue.  Is there a symantic distinction between `optional: false` and `optimal: nil`, or are we just inconsistent about which one we use?  If the former, then this probably makes sense, but if the latter, I'd prefer to correct/standardize the data rather than paper over it.

Comment (emilia-friedberg) [reply services/QuillCMS/app/controllers/responses_controller.rb]: There is a semantic difference. Only human-graded responses can be `optimal: false` - the algorithms don't know whether a response is right or wrong. For the most part, algorithmically-graded answers are suboptimal, but we do have some instances in the diagnostic where focus points and incorrect sequences are used to find to only apply correct concept results.

Comment (emilia-friedberg) [reply services/QuillCMS/app/controllers/responses_controller.rb]: The issue that this PR is fixing is that there aren't always human-graded suboptimal answers, to further clarify.

Comment (anathomical) [reply services/QuillCMS/app/controllers/responses_controller.rb]: That makes sense.  In the longer-term, like once we have Comprehension, the assumption that algorithm-graded answers must always be sub-optimal may not hold true, but it's certainly true for now, so this seems like a good approach.
