### PR TITLE
Fix #2938: fix some more bugs popping up on NewRelic

### LINKED ISSUE #2938: Investigate NewRelic errors
- [x] https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/02457ede-9599-11e7-b844-0242ac11000f_0_3922
- [x] https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/d66a1adc-9593-11e7-b844-0242ac11000f_3925_7861
- [x] https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/002bb255-95a0-11e7-b844-0242ac11000f_0_4491

Two of these were not fixed in the last release, and one is new resulting from another error being fixed.

### PR DESCRIPTION
**Pull request by jaredsilver**

### CODE REVIEW

File: app/controllers/auth/google_controller.rb [hunk 1]
```diff
@@ -40,9 +40,9 @@ def google_login(email, access_token, google_id)
       sign_in(user)
       TestForEarnedCheckboxesWorker.perform_async(user.id)
       GoogleStudentImporterWorker.perform_async(current_user.id, session[:google_access_token])
-      redirect_to profile_path
+      return redirect_to profile_path
     else
-      redirect_to new_account_path
+      return redirect_to new_account_path
```
Comment (ddmck) [inline app/controllers/auth/google_controller.rb]: Why should we do this rather than just calling redirect to?

File: app/controllers/auth/google_controller.rb [hunk 2]
```diff
@@ -68,8 +68,7 @@ def register_with_google(name, email, role, access_token, google_id)
     email = email.downcase
     if current_user && current_user.email.downcase != email
       session[:google_email] = email
-      redirect_to "/auth/google_email_mismatch/"
-      return
+      return redirect_to "/auth/google_email_mismatch/"
```
Comment (ddmck) [inline app/controllers/auth/google_controller.rb]: I understand why having a return after a redirect_to is probably pointless, but why return the redirect?

File: app/controllers/auth/google_controller.rb (hunk 1 above)
Comment (jaredsilver) [reply app/controllers/auth/google_controller.rb]: `redirect_to` doesn't actually return on its own, so these methods think they're supposed to also be rendering something otherwise.

**Comment by ddmck** [comment]
Ok, great

**Comment by jaredsilver** [comment]
On second thought, let me take a second look at the `return redirect_to`s tomorrow. There were instances in here where multiple redirects and renders were occurring, but I need to double-check that what I changed won't break anything else.

File: app/controllers/auth/google_controller.rb (hunk 1 above)
Comment (jaredsilver) [reply app/controllers/auth/google_controller.rb]: Looking at this again now. Lines 43 and 45 shouldn't need a `return` because `google_login` is only ever called at the end of a non-rendering method, but I feel it's better to be explicit about it now in case we move something around in here later and forget to add the return.

File: app/controllers/auth/google_controller.rb (hunk 2 above)
Comment (jaredsilver) [reply app/controllers/auth/google_controller.rb]: Having the return on the same line as the redirect is just terser and more Rubyish. Also, keeping them together helps ensure we don't accidentally try to do some stuff afterward that results in a double render or double redirect error.

File: app/controllers/auth/google_controller.rb [hunk 3]
```diff
@@ -82,18 +81,15 @@ def register_with_google(name, email, role, access_token, google_id)
         end
       end
       if @user.errors.any?
-        redirect_to new_account_path
-        return
+        return redirect_to new_account_path
```
Comment (jaredsilver) [inline app/controllers/auth/google_controller.rb]: Ditto above.

File: app/controllers/auth/google_controller.rb [hunk 4]
```diff
@@ -82,18 +81,15 @@ def register_with_google(name, email, role, access_token, google_id)
...
       else
         @user.update(signed_up_with_google: true, google_id: google_id)
         if request.referer && URI(request.referer) &&
           (URI(request.referer).path == '/teachers/classrooms/dashboard' || URI(request.referer).path == '/teachers/classrooms/new')
           # if they are hitting this route through the dashboard or new classrooms page, they should be brought to the google sync page
-          redirect_to '/teachers/classrooms/google_sync'
-          return
+          return redirect_to '/teachers/classrooms/google_sync'
```
Comment (jaredsilver) [inline app/controllers/auth/google_controller.rb]: Ditto above.

File: app/controllers/auth/google_controller.rb [hunk 5]
```diff
@@ -82,18 +81,15 @@ def register_with_google(name, email, role, access_token, google_id)
...
         end
-        redirect_to profile_path
-        return
+        return redirect_to profile_path
```
Comment (jaredsilver) [inline app/controllers/auth/google_controller.rb]: Ditto above.

File: app/controllers/auth/google_controller.rb [hunk 6]
```diff
@@ -72,7 +73,9 @@ def register_with_google(name, email, role, access_token, google_id)
     else
       @user = User.find_or_initialize_by(email: email)
       if @user.new_record?
-        new_google_user(name, email, role, access_token, google_id, @user)
+        if !new_google_user(name, email, role, access_token, google_id, @user)
```
Comment (jaredsilver) [inline app/controllers/auth/google_controller.rb]: I'm not sure if I like this (there's probably a better way to do this), but this would allow `register_with_google` to manage all of the redirects and avoid a double-redirect in the case where `new_google_user` doesn't actually save the user.

I want to test this on staging first to make sure it works properly though.

Comment (jaredsilver) [reply app/controllers/auth/google_controller.rb]: Okay, looks like this works alright.
