### PR TITLE
fix #4770 - allow students to move on from fill in blank after optimal response

### LINKED ISSUE #4770: Bug Report: Connect Fill in the Blank requiring 5 attempts even with optimal responses
**Describe the bug**
When a student inputs an optimal response to a fill in the blank question on Connect, the student is not moved on to the next question. The student is required to recheck answer up to 5 times. 

**To Reproduce**
1. Go to https://connect.quill.org/#/admin/fill-in-the-blanks/-LFrRT8PtwWFp0DPzGEf/test
2. Submit an optimal response

**Impact**
Low impact currently. We only have a handful of fill in the blank activities, and I've moved them out of production until the issue is resolved. 

**Screenshots**
Recording: http://recordit.co/RjUAKReav8

### PR DESCRIPTION
**Pull request by emilia-friedberg**
Addresses issue #4770

**Changes proposed in this pull request:**
- stop preventing students from moving on before four submissions for fill in blank question

**If this is a visual change please attach screencaps of the new branch, making sure to censor user data**

**Has this branch been QA'd on staging?**  no

**Have you updated the docs?** no

**Have the tests been updated?** no

**Reviewer:** @ddmck

### CODE REVIEW

File: services/QuillConnect/app/components/studentLessons/fillInBlank.tsx [hunk 1]
```diff
@@ -314,8 +314,7 @@ export class PlayFillInTheBlankQuestion extends React.Component<any, any> {
   showNextQuestionButton() {
     const { question, } = this.props;
     const latestAttempt = this.getLatestAttempt();
-    const readyForNext =
-      question.attempts ? question.attempts.length > 4 : false || (latestAttempt && latestAttempt.response.optimal);
+    const readyForNext = question.attempts.length > 4 || (latestAttempt && latestAttempt.response.optimal);
```
Comment (ddmck) [inline services/QuillConnect/app/components/studentLessons/fillInBlank.tsx]:
```suggestion
    const readyForNext = (question.attempts && question.attempts.length > 4) || (latestAttempt && latestAttempt.response.optimal);
```
