### PR TITLE
Closes #841, add concept result stats to scorebook activity tooltip

### LINKED ISSUE #841: Tooltip on Scorebook: Add concepts breakdown
Include a list of 0-level concepts in the tooltip. Include correct/incorrect counts alongside each concept.

### PR DESCRIPTION
**Pull request by kriskelly**

### CODE REVIEW

File: app/models/scorebook.rb [hunk 1]
```diff
@@ -0,0 +1,97 @@
+class Scorebook
```
Comment (marcellosachs) [inline app/models/scorebook.rb]: @kriskelly liking the OOP town. Perhaps we can put this in a folder app/queries ?

File: app/serializers/concept_result_serializer.rb [hunk 2]
```diff
@@ -0,0 +1,7 @@
+class ConceptResultSerializer < ActiveModel::Serializer
+  attributes :concept_name, :metadata
+
+  def concept_name
```
Comment (marcellosachs) [inline app/serializers/concept_result_serializer.rb]: @kriskelly how about adding a line `belongs_to :concept` under the `attributes` line, this way concept name can be fetched with concept_result.concept.name ?

File: app/models/scorebook.rb (hunk 1 above)
Comment (kriskelly) [inline app/models/scorebook.rb]: @marcellosachs That could work, I feel like it's basically a model, though not an ActiveRecord model. I'd be inclined to leave it but maybe change the name to something like `ScorebookQuery`?

File: app/serializers/concept_result_serializer.rb (hunk 2 above)
Comment (kriskelly) [inline app/serializers/concept_result_serializer.rb]: ah good call

File: app/models/scorebook.rb (hunk 1 above)
Comment (marcellosachs) [inline app/models/scorebook.rb]: @kriskelly Since the models folder is already pretty crowded, it'd be nice to categorize ruby classes into other folders where we can, keeping models/ for ActiveRecord. Apparently a 'queries' folder is something people do (http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/)

Comment (kriskelly) [inline app/models/scorebook.rb]: @marcellosachs okie dokie
