### PR TITLE
fix  #5145 - update link to lesson preview from diagnostic recommendations page

### LINKED ISSUE #5145: Bug Report: Cannot Preview Lessons from Diagnostic Recommendations Page
**Describe the bug**
When teachers select the “Preview Lesson” button from the “Teacher-Led Activity Recommendations” section of the “Recommendations” page, it just brings teachers to the “customize lesson” page and doesn’t allow them to preview the Lesson.

**Additional context**
https://docs.google.com/document/d/1OQy8R-Ra3Pu4L3bZrpSQoyGZ2Zm5-1QrylQm8egBnhQ/edit?usp=sharing

### PR DESCRIPTION
**Pull request by emilia-friedberg**
Addresses issue #5145

**Changes proposed in this pull request:**
- update link to lessons preview from diagnostic recommendations page

**If this is a visual change please attach screencaps of the new branch, making sure to censor user data**

**Has this branch been QA'd on staging?** no

**Have you updated the docs?** no

**Have the tests been updated?** no

**Reviewer:** @anathomical

### CODE REVIEW

File: services/QuillLMS/app/queries/lesson_recommendations_query.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def recommendations
   end
 
   def get_activities(rec_id)
-    activities = ActiveRecord::Base.connection.execute("SELECT activities.name, activities.uid, activity_classifications.form_url
+    activities = ActiveRecord::Base.connection.execute("SELECT activities.name, activities.id
```
Comment (anathomical) [inline services/QuillLMS/app/queries/lesson_recommendations_query.rb]: I wanted to call out that I appreciate you trimming this query down so that it doesn't pull columns we don't need anymore in additional to adding the new column you need.

That said, do we need the join on `activity_classifications` in this anymore since we don't pull the column anymore?
